#!/bin/bash

# set up symlinks
echo "creating symlinks"
dotfiles=( vim bashrc gemrc git-completion.bash git-prompt.sh gitconfig tmux.conf vimrc )
for file in "${dotfiles[@]}"
do
  path="$(pwd)/$file"
  target="$HOME/.$file"

  if [ -e $target ]; then
    read -p "$target exists, overwrite? [yn]" -n 1

    if [[ $REPLY =~ [yY] ]]; then
      echo "symlinking $path to $target"
      ln -sf $path $target
    fi
  fi
done

# for vim tmp files
echo "creating tmp directory for vim files"
mkdir ~/tmp

# pull submodules
echo "updating submodules"
git pull && git submodule init && git submodule update && git submodule status

# get vim
echo "building vim from source"
hg clone https://vim.googlecode.com/hg/ $HOME/vimsrc
cd $HOME/vimsrc
./configure --prefix=/usr/local \
  --enable-gui=no \
  --without-x \
  --disable-nls \
  --enable-multibyte \
  --with-tlib=ncurses \
  --enable-pythoninterp \
  --with-python-config-dir=/usr/lib/python2.7/config \
  --enable-rubyinterp \
  --with-ruby-command=/usr/lib/shopify-ruby/2.0.0-p353/bin/ruby \
  --with-features=huge
make
sudo make install

# compile command t
echo "compiling command t vim plugin"
cd $HOME/.vim/bundle/command-t/ruby/command-t
ruby extconf.rb
make
